apiVersion: v1
kind: Service
metadata:
  name: website
  labels:
    {{- include "panoramax.labels" . | nindent 4 }}
spec:
  selector:
    app: website
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
