apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm
  labels:
    {{- include "panoramax.labels" . | nindent 4 }}
data:
  keycloak-realm.json: |
{{ .Files.Get "files/keycloak-realm.json" | indent 4 }}
