apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    {{- include "panoramax.labels" . | nindent 4 }}
spec:
  selector:
    app: api
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
