name: Lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: azure/setup-helm@v5

      - name: make lint
        run: make lint

      - name: make dry-run
        run: make dry-run

      - name: yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .
          config_data: |
            extends: default
            ignore: |
              templates/
            rules:
              line-length: disable
              truthy: disable
