name: Lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: azure/setup-helm@v4

      - name: helm lint
        run: helm lint .

      - name: helm template (dry render)
        run: |
          helm template panoramax . \
            --set apiExternalUrl=http://example.com:5000 \
            --set authExternalUrl=http://example.com:8182

      - name: yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .
          config_data: |
            extends: default
            rules:
              line-length: disable
              truthy: disable
